CREATE TABLE `TBL_EXCEPTION` (
  `ID` mediumint(9) NOT NULL AUTO_INCREMENT,
  `ROOT_CAUSE` varchar(200) NOT NULL,
  `MESSAGE` varchar(500) NOT NULL,
  `CREATION_DATE` datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP,
  `AFFECTED_USER` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;
CREATE TABLE `TBL_AUTHORITY` (
  `ID` mediumint(9) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(20) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;
CREATE TABLE `TBL_USER` (
  `ID` mediumint(9) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(20) NOT NULL,
  `PASSWORD` varchar(100) NOT NULL DEFAULT '',
  `FIRST_NAME` varchar(50) NOT NULL,
  `LAST_NAME` varchar(50) NOT NULL,
  `ENABLED` tinyint(1) NOT NULL DEFAULT '1',
  `EMAIL` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
CREATE TABLE `TBL_USER_AUTHORITY` (
  `USER_ID` mediumint(9) NOT NULL,
  `AUTHORITY_ID` mediumint(9) NOT NULL,
  PRIMARY KEY (`USER_ID`,`AUTHORITY_ID`),
  KEY `AUTHORITY_ID` (`AUTHORITY_ID`),
  CONSTRAINT `TBL_USER_AUTHORITY_ibfk_1` FOREIGN KEY (`USER_ID`) REFERENCES `TBL_USER` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `TBL_USER_AUTHORITY_ibfk_2` FOREIGN KEY (`AUTHORITY_ID`) REFERENCES `TBL_AUTHORITY` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO TBL_AUTHORITY VALUES (1, 'ROLE_USER');
INSERT INTO TBL_AUTHORITY VALUES (2, 'ROLE_ADMIN');
/*pass=admin*/
INSERT INTO TBL_USER VALUES (1, 'jeocampo','$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi','Jorge','Ocampo',1,'jocampo@moneyxchange.io' );

INSERT INTO TBL_USER_AUTHORITY VALUES (1,1);
